
platform :ios, '13.0'

target 'TestPodspecModules' do
    use_frameworks!

    pod 'Life360AdsSDK'
    pod 'Life360AdsSDKAdMobAdapters'
    pod 'Life360AdsSDKGAMEventHandlers'
    pod 'Life360AdsSDKMAXAdapters'
end
